import type { Freebie } from '@/types/freebie';

const CREATOR = { id: 1, name: 'Alex Chapman', avatar: '/images/creator-avatar.jpg' };
const NOW = new Date().toISOString();

export const MOCK_FREEBIES: Freebie[] = [
  {
    id: '1',
    title: 'Digital marketing for beginners',
    description: 'Description description description description description',
    creator: CREATOR,
    creatorId: 1,
    creatorName: 'Alex Chapman',
    estimatedReadingTime: 3,
    downloadCount: 28000,
    createdAt: NOW,
    saved: false,
    price: 0,
    currency: 'NGN',
    purchased: false,
    items: [
      { id: 'f1', itemType: 'file', fileName: 'Module 1. Introduction', fileType: 'pdf', fileSize: 460800, downloadCount: 0, isFreePreview: false },
      { id: 'f2', itemType: 'file', fileName: 'Training Day 1', fileType: 'mp4', fileSize: 131072000, downloadCount: 0, isFreePreview: false },
    ],
  },
  {
    id: '2',
    title: 'Advanced SEO strategies',
    description: 'Description description description description description',
    creator: CREATOR,
    creatorId: 1,
    creatorName: 'Alex Chapman',
    estimatedReadingTime: 5,
    downloadCount: 28000,
    createdAt: NOW,
    saved: true,
    price: 0,
    currency: 'NGN',
    purchased: false,
    items: [
      { id: 'f5', itemType: 'file', fileName: 'Module 1. Introduction', fileType: 'pdf', fileSize: 327680, downloadCount: 0, isFreePreview: false },
    ],
  },
  {
    id: '3',
    title: 'Content creation masterclass',
    description: 'Description description description description description',
    creator: CREATOR,
    creatorId: 1,
    creatorName: 'Alex Chapman',
    estimatedReadingTime: 4,
    downloadCount: 28000,
    createdAt: NOW,
    saved: false,
    price: 0,
    currency: 'NGN',
    purchased: false,
    items: [
      { id: 'f7', itemType: 'file', fileName: 'Module 1. Introduction', fileType: 'pdf', fileSize: 524288, downloadCount: 0, isFreePreview: false },
    ],
  },
  {
    id: '4',
    title: 'Social media growth guide',
    description: 'Description description description description description',
    creator: CREATOR,
    creatorId: 1,
    creatorName: 'Alex Chapman',
    estimatedReadingTime: 2,
    downloadCount: 28000,
    createdAt: NOW,
    saved: true,
    price: 0,
    currency: 'NGN',
    purchased: false,
    items: [
      { id: 'f11', itemType: 'file', fileName: 'Complete Guide', fileType: 'pdf', fileSize: 1258291, downloadCount: 0, isFreePreview: false },
    ],
  },
  {
    id: '5',
    title: 'Email marketing fundamentals',
    description: 'Description description description description description',
    creator: CREATOR,
    creatorId: 1,
    creatorName: 'Alex Chapman',
    estimatedReadingTime: 6,
    downloadCount: 28000,
    createdAt: NOW,
    saved: false,
    price: 0,
    currency: 'NGN',
    purchased: false,
    items: [
      { id: 'f12', itemType: 'file', fileName: 'Intro Slides', fileType: 'pdf', fileSize: 2097152, downloadCount: 0, isFreePreview: false },
      { id: 'f13', itemType: 'link', linkTitle: 'Video Tutorial', linkUrl: 'https://example.com', downloadCount: 0, isFreePreview: false },
    ],
  },
];
