import type { VideoDetail } from '@/types/video';

// Extended mock data for video details
export const videoDetailsData: Record<string, VideoDetail> = {
  '1': {
    id: '1',
    title: 'Quiz Game Contest by Learning247',
    description: 'Join our exciting quiz game contest and test your knowledge across various topics. Win amazing prizes and compete with students worldwide!',
    thumbnail: '/courses/data-analysis-complete.svg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    author: 'Learning247 Team',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Join our exciting quiz game contest and test your knowledge across various topics. Win amazing prizes and compete with students worldwide!',
    duration: 45,
    postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    rating: 4.9,
    ratingCount: 15000,
    category: 'Gaming',
    tags: ['quiz', 'contest', 'gaming'],
    price: 0,
    isLive: false,
    classStartDate: new Date(Date.now() + 17 * 60 * 60 * 1000 + 32 * 60 * 1000 + 19 * 1000),
    viewsCount: 13000,
    userId: 'learning247-team', // Creator ID for access control
  },
  '2': {
    id: '2',
    title: 'Graphic Design PRO',
    description: 'Scale up your design skills to match modern styles with modern tools',
    thumbnail: '/courses/data-analysis-complete.svg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    author: 'Alex Chapman',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Scale up your design skills to match modern styles with modern tools. Learn professional techniques used by top designers.',
    duration: 120,
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    rating: 4.8,
    ratingCount: 20000,
    category: 'Design',
    tags: ['graphic design', 'adobe', 'creative'],
    price: 16,
    isLive: true,
    classStartDate: new Date(Date.now() + 5 * 60 * 60 * 1000 + 45 * 60 * 1000),
    viewsCount: 25000,
    userId: 'alex-chapman-123', // Creator ID for access control
  },
  '3': {
    id: '3',
    title: 'Graphic Design PRO',
    description: 'Scale up your design skills to match modern styles with modern tools',
    thumbnail: '/courses/marketing-strategy.svg',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    author: 'Alex Chapman',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Master the art of graphic design with industry-standard tools and techniques.',
    duration: 120,
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    rating: 4.8,
    ratingCount: 20000,
    category: 'Design',
    tags: ['design', 'marketing'],
    price: 16,
    isLive: false,
    classStartDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    viewsCount: 18000,
    userId: 'alex-chapman-123', // Creator ID for access control
  },
  '4': {
    id: '4',
    title: 'Graphic Design PRO',
    description: 'Scale up your design skills to match modern styles with modern tools',
    thumbnail: '/courses/creative-graphic-design.svg',
    videoUrl: '',
    author: 'Alex Chapman',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Transform your creative ideas into stunning visual designs.',
    duration: 120,
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    rating: 4.8,
    ratingCount: 20000,
    category: 'Design',
    tags: ['creative', 'design'],
    price: 16,
    isLive: true,
    classStartDate: new Date(Date.now() + 3 * 60 * 60 * 1000),
    viewsCount: 22000,
    userId: 'alex-chapman-123', // Creator ID for access control
  },
  '5': {
    id: '5',
    title: 'Digital Marketing Tutorial for Beginners',
    description: 'Learn the basics of digital marketing and grow your online presence',
    thumbnail: '/shorts/marketing-basics.jpg',
    videoUrl: '',
    author: 'Marketing Expert',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Learn the basics of digital marketing and grow your online presence with proven strategies.',
    duration: 15,
    postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    rating: 4.7,
    ratingCount: 10000,
    category: 'Marketing',
    tags: ['digital marketing', 'beginners'],
    price: 0,
    isLive: false,
    viewsCount: 10000,
    userId: 'marketing-expert-456', // Creator ID for access control
  },
  '10': {
    id: '10',
    title: 'Graphic Design PRO',
    description: 'Scale up your design skills to match modern styles with modern tools',
    thumbnail: '/courses/advertising-beyond.svg',
    videoUrl: '',
    author: 'Alex Chapman',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Advanced graphic design course covering modern design principles and tools.',
    duration: 120,
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    rating: 4.8,
    ratingCount: 20000,
    category: 'Design',
    tags: ['graphic design', 'advanced'],
    price: 16,
    isLive: false,
    classStartDate: new Date(Date.now() + 48 * 60 * 60 * 1000),
    viewsCount: 30000,
    userId: 'alex-chapman-123', // Creator ID for access control
  },
  '11': {
    id: '11',
    title: 'Graphic Design PRO',
    description: 'Scale up your design skills to match modern styles with modern tools',
    thumbnail: '/courses/data-visualization.svg',
    videoUrl: '',
    author: 'Alex Chapman',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Learn data visualization techniques for impactful design presentations.',
    duration: 120,
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    rating: 4.8,
    ratingCount: 20000,
    category: 'Design',
    tags: ['data visualization', 'design'],
    price: 16,
    isLive: true,
    classStartDate: new Date(Date.now() + 6 * 60 * 60 * 1000),
    viewsCount: 28000,
    userId: 'alex-chapman-123', // Creator ID for access control
  },
  '12': {
    id: '12',
    title: 'Graphic Design PRO',
    description: 'Scale up your design skills to match modern styles with modern tools',
    thumbnail: '/courses/ai-marketing-limits.svg',
    videoUrl: '',
    author: 'Alex Chapman',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Explore AI-powered design tools and their applications in modern marketing.',
    duration: 120,
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    rating: 4.8,
    ratingCount: 20000,
    category: 'Design',
    tags: ['ai', 'marketing', 'design'],
    price: 16,
    isLive: false,
    classStartDate: new Date(Date.now() + 72 * 60 * 60 * 1000),
    viewsCount: 19000,
    userId: 'alex-chapman-123', // Creator ID for access control
  },
  '13': {
    id: '13',
    title: 'Graphic Design PRO',
    description: 'Scale up your design skills to match modern styles with modern tools',
    thumbnail: '/courses/google-ads-guide.svg',
    videoUrl: '',
    author: 'Alex Chapman',
    authorAvatar: '/avatars/alex-chapman-instructor.jpg',
    authorBio: 'Master Google Ads design and create compelling ad campaigns.',
    duration: 120,
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    rating: 4.8,
    ratingCount: 20000,
    category: 'Marketing',
    tags: ['google ads', 'advertising'],
    price: 16,
    isLive: false,
    classStartDate: new Date(Date.now() + 96 * 60 * 60 * 1000),
    viewsCount: 17000,
    userId: 'alex-chapman-123', // Creator ID for access control
  },
};

// Function to get video details by ID
export function getVideoDetailsById(id: string): VideoDetail | null {
  return videoDetailsData[id] || null;
}